# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('fc44d44d14cf63233b15193de0e7142f_MjcyMTkyMDExLTA5LTEzIDA1OjA1OjUyLjQ2NDg4Nw')
  end)
end
